CREATE DATABASE CASTELLOVERS;

USE CASTELLOVERS;

CREATE TABLE IF NOT EXISTS ALUNOS (
    ID_ALUNO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    CPF CHAR(14) NOT NULL UNIQUE,
    STATUS_ALUNO ENUM('ATIVO', 'INATIVO', 'CONCLUÍDO') DEFAULT 'ATIVO',
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- VISUALIZAR TODOS OS BD
SHOW SCHEMAS;

-- VISUALIZAR TABELAS DO BD
SHOW TABLES;

-- DESCRIÇÃO DE ATRIBUTOS DA TABELA ALUNO
DESCRIBE ALUNOS;

-- APAGAR BD
DROP DATABASE CASTELLOVERS;